"""add task due_date

Revision ID: 8ac23a6b0baa
Revises: b9844da9d013
Create Date: 2026-05-01 21:50:31.541890

"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '8ac23a6b0baa'
down_revision: str | None = 'b9844da9d013'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('due_date', sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f('ix_tasks_due_date'), 'tasks', ['due_date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tasks_due_date'), table_name='tasks')
    op.drop_column('tasks', 'due_date')
    # ### end Alembic commands ###
