"""add user role

Revision ID: c64db0184667
Revises: 04f50a6400f9
Create Date: 2026-05-02 05:29:24.583825

"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = 'c64db0184667'
down_revision: str | None = '04f50a6400f9'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # 3-step add for an existing table: nullable → backfill → NOT NULL.
    op.add_column("users", sa.Column("role", sa.String(length=16), nullable=True))
    op.execute("UPDATE users SET role = 'parent' WHERE role IS NULL")
    op.alter_column("users", "role", nullable=False)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'role')
    # ### end Alembic commands ###
