"""Italian saint-of-the-day calendar.

Maps every (month, day) of the year to the principal Catholic saint(s)
celebrated that day in the Italian Roman Calendar. The list focuses on
the saint most commonly named in Italian usage — schools, anagrafe,
"buon onomastico" etc. — rather than the full martyrology.

Sources: Roman Calendar (CEI), Wikipedia "Calendario dei santi" (it),
and the Italian Episcopal Conference's liturgical calendar. February 29
is paired with Sant'Osvaldo so leap days have a name.

Used by `cara.services.wall.build_calendar_grid` to render "santo del
giorno" under each calendar cell.
"""

from __future__ import annotations

from datetime import date


# (month, day) → "Saint Name" (or two names separated by " e ")
_SAINTS: dict[tuple[int, int], str] = {
    # ─── Gennaio ────────────────────────────────────────────────
    (1, 1): "Maria Madre di Dio",
    (1, 2): "San Basilio Magno",
    (1, 3): "Santa Genoveffa",
    (1, 4): "Sant'Ermete",
    (1, 5): "Sant'Amelia",
    (1, 6): "Epifania",
    (1, 7): "San Raimondo",
    (1, 8): "San Massimo",
    (1, 9): "Sant'Adriano",
    (1, 10): "Sant'Aldo",
    (1, 11): "Sant'Igino",
    (1, 12): "Sant'Arcadio",
    (1, 13): "Sant'Ilario",
    (1, 14): "San Felice da Nola",
    (1, 15): "San Mauro abate",
    (1, 16): "San Marcello I",
    (1, 17): "Sant'Antonio Abate",
    (1, 18): "Santa Margherita d'Ungheria",
    (1, 19): "San Mario",
    (1, 20): "San Sebastiano",
    (1, 21): "Sant'Agnese",
    (1, 22): "San Vincenzo",
    (1, 23): "Sant'Emerenziana",
    (1, 24): "San Francesco di Sales",
    (1, 25): "Conversione di San Paolo",
    (1, 26): "Santi Tito e Timoteo",
    (1, 27): "Sant'Angela Merici",
    (1, 28): "San Tommaso d'Aquino",
    (1, 29): "San Costanzo",
    (1, 30): "Santa Martina",
    (1, 31): "San Giovanni Bosco",

    # ─── Febbraio ───────────────────────────────────────────────
    (2, 1): "Santa Verdiana",
    (2, 2): "Presentazione del Signore",
    (2, 3): "San Biagio",
    (2, 4): "Sant'Andrea Corsini",
    (2, 5): "Sant'Agata",
    (2, 6): "San Paolo Miki",
    (2, 7): "San Riccardo",
    (2, 8): "San Girolamo Emiliani",
    (2, 9): "Sant'Apollonia",
    (2, 10): "Santa Scolastica",
    (2, 11): "Madonna di Lourdes",
    (2, 12): "Santa Eulalia",
    (2, 13): "Santa Fosca",
    (2, 14): "San Valentino",
    (2, 15): "San Faustino",
    (2, 16): "Santa Giuliana",
    (2, 17): "Sette Santi Fondatori dei Servi di Maria",
    (2, 18): "San Simeone",
    (2, 19): "San Mansueto",
    (2, 20): "San Eleuterio",
    (2, 21): "San Pier Damiani",
    (2, 22): "Cattedra di San Pietro",
    (2, 23): "San Policarpo",
    (2, 24): "San Mattia",
    (2, 25): "San Cesario",
    (2, 26): "Sant'Alessandro",
    (2, 27): "San Gabriele dell'Addolorata",
    (2, 28): "San Romano",
    (2, 29): "Sant'Osvaldo",  # leap day

    # ─── Marzo ──────────────────────────────────────────────────
    (3, 1): "Sant'Albino",
    (3, 2): "San Quinto",
    (3, 3): "San Cunegonda",
    (3, 4): "San Casimiro",
    (3, 5): "San Adriano di Cesarea",
    (3, 6): "Santa Coletta",
    (3, 7): "Sante Perpetua e Felicita",
    (3, 8): "San Giovanni di Dio",
    (3, 9): "Santa Francesca Romana",
    (3, 10): "San Simplicio",
    (3, 11): "San Costantino",
    (3, 12): "San Massimiliano",
    (3, 13): "Sant'Eufrasia",
    (3, 14): "Santa Matilde",
    (3, 15): "Santa Luisa de Marillac",
    (3, 16): "Sant'Eriberto",
    (3, 17): "San Patrizio",
    (3, 18): "San Cirillo di Gerusalemme",
    (3, 19): "San Giuseppe",
    (3, 20): "Sant'Alessandra",
    (3, 21): "San Nicola di Flue",
    (3, 22): "Santa Lea",
    (3, 23): "San Turibio",
    (3, 24): "Santa Caterina di Svezia",
    (3, 25): "Annunciazione del Signore",
    (3, 26): "San Manuele",
    (3, 27): "Sant'Augusto",
    (3, 28): "San Sisto III",
    (3, 29): "San Secondo",
    (3, 30): "San Leonardo Murialdo",
    (3, 31): "San Beniamino",

    # ─── Aprile ─────────────────────────────────────────────────
    (4, 1): "Sant'Ugo di Grenoble",
    (4, 2): "San Francesco da Paola",
    (4, 3): "San Riccardo",
    (4, 4): "Sant'Isidoro di Siviglia",
    (4, 5): "San Vincenzo Ferrer",
    (4, 6): "San Pietro da Verona",
    (4, 7): "San Giovanni Battista de la Salle",
    (4, 8): "San Walter",
    (4, 9): "Santa Maria di Cleofa",
    (4, 10): "Sant'Ezechiele",
    (4, 11): "San Stanislao",
    (4, 12): "San Giulio I",
    (4, 13): "San Martino I",
    (4, 14): "Sant'Abbondio",
    (4, 15): "Sant'Annibale",
    (4, 16): "Santa Bernadette",
    (4, 17): "Sant'Aniceto",
    (4, 18): "San Galdino",
    (4, 19): "Sant'Emma",
    (4, 20): "Sant'Adalgisa",
    (4, 21): "Sant'Anselmo d'Aosta",
    (4, 22): "San Caio",
    (4, 23): "San Giorgio",
    (4, 24): "San Fedele da Sigmaringa",
    (4, 25): "San Marco evangelista",
    (4, 26): "San Marcellino",
    (4, 27): "Santa Zita",
    (4, 28): "San Pietro Chanel",
    (4, 29): "Santa Caterina da Siena",
    (4, 30): "San Pio V",

    # ─── Maggio ─────────────────────────────────────────────────
    (5, 1): "San Giuseppe lavoratore",
    (5, 2): "Sant'Atanasio",
    (5, 3): "Santi Filippo e Giacomo",
    (5, 4): "San Floriano",
    (5, 5): "Sant'Irene",
    (5, 6): "San Domenico Savio",
    (5, 7): "Santa Flavia",
    (5, 8): "San Vittore",
    (5, 9): "San Pacomio",
    (5, 10): "San Giobbe",
    (5, 11): "San Fabio",
    (5, 12): "Santi Nereo e Achilleo",
    (5, 13): "Madonna di Fatima",
    (5, 14): "San Mattia apostolo",
    (5, 15): "Sant'Isidoro contadino",
    (5, 16): "Sant'Ubaldo",
    (5, 17): "San Pasquale Baylon",
    (5, 18): "San Giovanni I",
    (5, 19): "San Celestino V",
    (5, 20): "San Bernardino da Siena",
    (5, 21): "San Vittorio",
    (5, 22): "Santa Rita da Cascia",
    (5, 23): "San Desiderio",
    (5, 24): "Maria Ausiliatrice",
    (5, 25): "San Beda il Venerabile",
    (5, 26): "San Filippo Neri",
    (5, 27): "Sant'Agostino di Canterbury",
    (5, 28): "San Germano",
    (5, 29): "Sant'Emilio",
    (5, 30): "Santa Giovanna d'Arco",
    (5, 31): "Visitazione di Maria",

    # ─── Giugno ─────────────────────────────────────────────────
    (6, 1): "San Giustino",
    (6, 2): "Santi Marcellino e Pietro",
    (6, 3): "San Carlo Lwanga",
    (6, 4): "San Quirino",
    (6, 5): "San Bonifacio",
    (6, 6): "San Norberto",
    (6, 7): "San Roberto",
    (6, 8): "San Medardo",
    (6, 9): "Sant'Efrem",
    (6, 10): "Santa Diana",
    (6, 11): "San Barnaba",
    (6, 12): "San Guido",
    (6, 13): "Sant'Antonio da Padova",
    (6, 14): "Sant'Eliseo",
    (6, 15): "Santa Germana",
    (6, 16): "San Aureliano",
    (6, 17): "San Ranieri",
    (6, 18): "San Marco e Marcelliano",
    (6, 19): "San Romualdo",
    (6, 20): "San Silverio",
    (6, 21): "San Luigi Gonzaga",
    (6, 22): "San Paolino da Nola",
    (6, 23): "San Lanfranco",
    (6, 24): "Natività di San Giovanni Battista",
    (6, 25): "San Massimo di Torino",
    (6, 26): "San Vigilio",
    (6, 27): "San Cirillo d'Alessandria",
    (6, 28): "Sant'Ireneo",
    (6, 29): "Santi Pietro e Paolo",
    (6, 30): "San Otto",

    # ─── Luglio ─────────────────────────────────────────────────
    (7, 1): "San Aronne",
    (7, 2): "Sant'Ottone",
    (7, 3): "San Tommaso apostolo",
    (7, 4): "Santa Elisabetta del Portogallo",
    (7, 5): "Sant'Antonio Maria Zaccaria",
    (7, 6): "Santa Maria Goretti",
    (7, 7): "San Claudio",
    (7, 8): "San Adriano III",
    (7, 9): "Santa Veronica",
    (7, 10): "Santa Felicita",
    (7, 11): "San Benedetto da Norcia",
    (7, 12): "Santa Giuliana",
    (7, 13): "Sant'Enrico",
    (7, 14): "San Camillo de Lellis",
    (7, 15): "San Bonaventura",
    (7, 16): "Madonna del Carmelo",
    (7, 17): "Santa Marcellina",
    (7, 18): "San Federico",
    (7, 19): "Santa Giusta",
    (7, 20): "Sant'Elia profeta",
    (7, 21): "San Lorenzo da Brindisi",
    (7, 22): "Santa Maria Maddalena",
    (7, 23): "Santa Brigida",
    (7, 24): "San Cristina",
    (7, 25): "San Giacomo apostolo",
    (7, 26): "Santi Gioacchino e Anna",
    (7, 27): "Santa Liliana",
    (7, 28): "San Nazario",
    (7, 29): "Santa Marta",
    (7, 30): "San Pietro Crisologo",
    (7, 31): "Sant'Ignazio di Loyola",

    # ─── Agosto ─────────────────────────────────────────────────
    (8, 1): "Sant'Alfonso Maria de' Liguori",
    (8, 2): "Sant'Eusebio di Vercelli",
    (8, 3): "Santa Lidia",
    (8, 4): "San Giovanni Maria Vianney",
    (8, 5): "Madonna della Neve",
    (8, 6): "Trasfigurazione del Signore",
    (8, 7): "San Sisto II",
    (8, 8): "San Domenico di Guzmán",
    (8, 9): "Santa Teresa Benedetta della Croce",
    (8, 10): "San Lorenzo",
    (8, 11): "Santa Chiara d'Assisi",
    (8, 12): "Santa Giovanna Francesca",
    (8, 13): "San Ponziano",
    (8, 14): "San Massimiliano Kolbe",
    (8, 15): "Assunzione di Maria",
    (8, 16): "San Rocco",
    (8, 17): "Sant'Eusebio di Roma",
    (8, 18): "Sant'Elena imperatrice",
    (8, 19): "San Giovanni Eudes",
    (8, 20): "San Bernardo di Chiaravalle",
    (8, 21): "San Pio X",
    (8, 22): "Beata Vergine Maria Regina",
    (8, 23): "Santa Rosa da Lima",
    (8, 24): "San Bartolomeo",
    (8, 25): "San Luigi IX",
    (8, 26): "Sant'Alessandro",
    (8, 27): "Santa Monica",
    (8, 28): "Sant'Agostino",
    (8, 29): "Martirio di San Giovanni Battista",
    (8, 30): "Santa Tecla",
    (8, 31): "San Raimondo Nonnato",

    # ─── Settembre ──────────────────────────────────────────────
    (9, 1): "Sant'Egidio abate",
    (9, 2): "Sant'Elpidio",
    (9, 3): "San Gregorio Magno",
    (9, 4): "Santa Rosalia",
    (9, 5): "Santa Teresa di Calcutta",
    (9, 6): "San Petronio",
    (9, 7): "Santa Regina",
    (9, 8): "Natività di Maria",
    (9, 9): "San Pietro Claver",
    (9, 10): "San Nicola da Tolentino",
    (9, 11): "Santi Proto e Giacinto",
    (9, 12): "Santo Nome di Maria",
    (9, 13): "San Giovanni Crisostomo",
    (9, 14): "Esaltazione della Santa Croce",
    (9, 15): "Maria Addolorata",
    (9, 16): "Santi Cornelio e Cipriano",
    (9, 17): "San Roberto Bellarmino",
    (9, 18): "San Giuseppe da Copertino",
    (9, 19): "San Gennaro",
    (9, 20): "Santi Andrea Kim e compagni martiri",
    (9, 21): "San Matteo apostolo",
    (9, 22): "San Maurizio",
    (9, 23): "San Pio da Pietrelcina",
    (9, 24): "Santa Tecla",
    (9, 25): "San Cleofa",
    (9, 26): "Santi Cosma e Damiano",
    (9, 27): "San Vincenzo de' Paoli",
    (9, 28): "San Venceslao",
    (9, 29): "Santi Arcangeli Michele, Gabriele, Raffaele",
    (9, 30): "San Girolamo",

    # ─── Ottobre ────────────────────────────────────────────────
    (10, 1): "Santa Teresa di Lisieux",
    (10, 2): "Santi Angeli Custodi",
    (10, 3): "San Gerardo",
    (10, 4): "San Francesco d'Assisi",
    (10, 5): "Santa Faustina Kowalska",
    (10, 6): "San Bruno",
    (10, 7): "Madonna del Rosario",
    (10, 8): "Santa Pelagia",
    (10, 9): "San Dionigi",
    (10, 10): "San Daniele",
    (10, 11): "San Giovanni XXIII",
    (10, 12): "San Serafino",
    (10, 13): "San Edoardo",
    (10, 14): "San Callisto I",
    (10, 15): "Santa Teresa d'Avila",
    (10, 16): "Santa Edvige",
    (10, 17): "Sant'Ignazio di Antiochia",
    (10, 18): "San Luca evangelista",
    (10, 19): "San Paolo della Croce",
    (10, 20): "Santa Irene",
    (10, 21): "Sant'Orsola",
    (10, 22): "San Giovanni Paolo II",
    (10, 23): "San Giovanni da Capestrano",
    (10, 24): "Sant'Antonio Maria Claret",
    (10, 25): "San Crispino",
    (10, 26): "Sant'Evaristo",
    (10, 27): "Santa Sabina",
    (10, 28): "Santi Simone e Giuda",
    (10, 29): "Sant'Onorato",
    (10, 30): "San Germano",
    (10, 31): "San Quintino",

    # ─── Novembre ───────────────────────────────────────────────
    (11, 1): "Tutti i Santi",
    (11, 2): "Commemorazione dei defunti",
    (11, 3): "San Martino de Porres",
    (11, 4): "San Carlo Borromeo",
    (11, 5): "San Zaccaria",
    (11, 6): "San Leonardo",
    (11, 7): "Sant'Ernesto",
    (11, 8): "Sant'Adeodato",
    (11, 9): "Dedicazione della Basilica Lateranense",
    (11, 10): "San Leone Magno",
    (11, 11): "San Martino di Tours",
    (11, 12): "San Giosafat",
    (11, 13): "San Diego",
    (11, 14): "San Giocondo",
    (11, 15): "Sant'Alberto Magno",
    (11, 16): "Santa Margherita di Scozia",
    (11, 17): "Santa Elisabetta d'Ungheria",
    (11, 18): "Dedicazione delle Basiliche dei Santi Pietro e Paolo",
    (11, 19): "Sant'Obadia",
    (11, 20): "San Edmondo",
    (11, 21): "Presentazione di Maria",
    (11, 22): "Santa Cecilia",
    (11, 23): "San Clemente I",
    (11, 24): "San Andrea Dung-Lac",
    (11, 25): "Santa Caterina d'Alessandria",
    (11, 26): "San Corrado",
    (11, 27): "San Virgilio",
    (11, 28): "San Giacomo della Marca",
    (11, 29): "San Saturnino",
    (11, 30): "Sant'Andrea apostolo",

    # ─── Dicembre ───────────────────────────────────────────────
    (12, 1): "Sant'Eligio",
    (12, 2): "Santa Bibiana",
    (12, 3): "San Francesco Saverio",
    (12, 4): "Santa Barbara",
    (12, 5): "San Saba",
    (12, 6): "San Nicola di Bari",
    (12, 7): "Sant'Ambrogio",
    (12, 8): "Immacolata Concezione",
    (12, 9): "San Siro",
    (12, 10): "Madonna di Loreto",
    (12, 11): "San Damaso I",
    (12, 12): "Madonna di Guadalupe",
    (12, 13): "Santa Lucia",
    (12, 14): "San Giovanni della Croce",
    (12, 15): "Santa Cristina",
    (12, 16): "Sant'Albina",
    (12, 17): "San Lazzaro",
    (12, 18): "San Graziano",
    (12, 19): "Sant'Anastasio I",
    (12, 20): "San Liberato",
    (12, 21): "San Pietro Canisio",
    (12, 22): "Santa Francesca Saverio Cabrini",
    (12, 23): "San Giovanni da Kety",
    (12, 24): "Sant'Adele",
    (12, 25): "Natale del Signore",
    (12, 26): "Santo Stefano",
    (12, 27): "San Giovanni evangelista",
    (12, 28): "Santi Innocenti martiri",
    (12, 29): "San Tommaso Becket",
    (12, 30): "San Felice I",
    (12, 31): "San Silvestro I",
}


def saint_for(d: date) -> str:
    """Return the Italian saint for a given date, or empty string."""
    return _SAINTS.get((d.month, d.day), "")


__all__ = ["saint_for"]
